### ISSUE TITLE
validate the input fields of the registration and login forms

### ISSUE THREAD

**Issue by HLena** [HLena/LIM012-fe-social-network#7]
Validation rules
**For the register form**
- Fill all fields of the form
- Enter a secure password (minimum 6 characters, must contain at least a number and a capital letter).
**For the login form**
- check that the email is linked to an existing account.
- enter a valid password for that account

If you do not comply with any of the above rules, display an error message according to the rule that is not satisfied

**Comment by RLCHuncp** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5ec9edbe3c50160016736df3/attachments/5ecac34aa24f5a00118389f8)
